- mod/Jailbreak.Warden/Global/WardenBehavior.cs
- mod/Jailbreak.Warden/WardenConfig.cs
- mod/Jailbreak.Warden/WardenServiceExtension.cs
sounds should be configurable, should check for real players, and should possibily move to a helper function within the notification subsystem
requires multiaddonmanager with this addon configured https://steamcommunity.com/sharedfiles/filedetails/?id=3156164769
will post addon to github later
> basic warden sound implementation

- mod/Jailbreak.Logs/Listeners/LogEntityListeners.cs
Reverts edgegamers/Jailbreak#112 - sigs out of date
> Revert "Add weapon drops to logs"

- public/Jailbreak.Public/Jailbreak.Public.csproj
need to cleanup some null reference warnings, but doesnt crash
> update cs# api

- mod/Jailbreak.SpecialDay/SpecialDayHandler.cs
- mod/Jailbreak.SpecialDay/SpecialDays/FreeForAllDay.cs
- mod/Jailbreak.SpecialDay/SpecialDays/Warday.cs
> Fix special days

- mod/Jailbreak.Rebel/JihadC4/JihadC4Behavior.cs
NOW I can call it a complete system (hopefully!)
Bugs that were fixed:
- Adjusted damage formula to reflect the original one in old bomb code, and made sure that damaging actually works
- Ensured giving bomb at start of round works properly now
- Very slight code improvement with TryGetValue()??
We still need to remove the debug command before it goes live :)
> Jihad C4 bug fix

- mod/Jailbreak.SpecialDay/Commands/SpecialDayCommandsBehavior.cs
Make special day command take no args
> Fix specialday command

- lang/Jailbreak.English/SpecialDay/SpecialDayNotifications.cs
- mod/Jailbreak.SpecialDay/SpecialDays/CustomDay.cs
- mod/Jailbreak.SpecialDay/SpecialDays/FreeForAllDay.cs
- mod/Jailbreak.SpecialDay/SpecialDays/Warday.cs
- mod/Jailbreak.Warden/Commands/WardenCommandsBehavior.cs
- public/Jailbreak.Formatting/Views/ISpecialDayNotifications.cs
- public/Jailbreak.Public/Utils/FreezeManager.cs
- src/Jailbreak/Jailbreak.cs
> Special day fixes

- mod/Jailbreak.LastRequest/LastRequestCommand.cs
- mod/Jailbreak.LastRequest/LastRequestManager.cs
This reverts commit d8e41156979747315baa8594a90de1864a495f0e, reversing changes made to a28094e97d4211937de133710549e175e8bcdf69.
> Revert "Fix/lr menu (#145)"

- mod/Jailbreak.Rebel/JihadC4/JihadC4Behavior.cs
I've disabled the push functionality and refined how +use is detected.
> potential bugfix jihadc4

- mod/Jailbreak.Rebel/JihadC4/JihadC4Behavior.cs
- mod/Jailbreak.Rebel/RebelServiceExtension.cs
- mod/Jailbreak.SpecialDay/SpecialDayHandler.cs
- mod/Jailbreak.SpecialDay/SpecialDays/CustomDay.cs
- mod/Jailbreak.SpecialDay/SpecialDays/FreeForAllDay.cs
- mod/Jailbreak.SpecialDay/SpecialDays/Freeday.cs
- mod/Jailbreak.SpecialDay/SpecialDays/Warday.cs
- public/Jailbreak.Public/Mod/Rebel/IJihadC4Service.cs
- public/Jailbreak.Public/Mod/SpecialDays/ISpecialDay.cs
- src/Jailbreak/Jailbreak.cs
- src/Jailbreak/JailbreakServiceCollection.cs
The new system doesn't try to manage the state of the bomb, it just listens to events and acts on that instead. 
This should fix all detection issues as well...
> refactored most of the code

- mod/Jailbreak.LastGuard/LastGuard.cs
Use PlayerPawn instead of the player controller to get and set the health
> Fix last issues with LastGuard

- mod/Jailbreak.LastRequest/LastRequestManager.cs
Fixes a lr bug where a player disconnects
> Fix LR bug

- lang/Jailbreak.English/LastRequest/LastRequestMessages.cs
- mod/Jailbreak.LastRequest/LastRequestManager.cs
- mod/Jailbreak.LastRequest/LastRequests/NoScope.cs
Resolves https://github.com/edgegamers/Jailbreak/issues/223
> Null check LR winners

- mod/Jailbreak.LastGuard/LastGuard.cs
- mod/Jailbreak.LastRequest/LastRequestManager.cs
- public/Jailbreak.Public/Mod/LastGuard/ILastGuardService.cs
- public/Jailbreak.Public/Utils/RoundUtil.cs
- Reduces Last Guard's HP ratio
- Adds configuration for managing the round timer when LG activates
> Manage round time when last guard activates

- mod/Jailbreak.Rebel/JihadC4/JihadC4Behavior.cs
- mod/Jailbreak.Warden/Global/WardenBehavior.cs
- Fixes LastGuard not stripping weapons
- Fixes CT buff not being applied
> Fix CT Buffs and Gun Toss LR

- mod/Jailbreak.SpecialDay/SpecialDays/GunGameDay.cs
- mod/Jailbreak.SpecialDay/SpecialDays/SpeedrunDay.cs
- Fixes slaying yourself granting a promotion
- Fixes speedrunners menu spacing / indexing
> Fix gun game and speedrunners menu

- mod/Jailbreak.SpecialDay/SpecialDays/FFADay.cs
- mod/Jailbreak.SpecialDay/SpecialDays/WardayDay.cs
- Increased FFA from 20 seconds to 40 starting time
- Increased Warday from 35 to 50 starting time
> Increased starting time for Warday and FFA

- mod/Jailbreak.LastRequest/LastRequests/BulletForBullet.cs
> Fix bullet for bullet lr

- mod/Jailbreak.LastGuard/LastGuard.cs
> Allow server owners to disable last guard

- mod/Jailbreak.LastRequest/LastRequests/BulletForBullet.cs
https://gitlab.edgegamers.io/source2/cs2/servers/jailbreak/-/issues/136
> Fix S4S/M4M LR (Switch EventBulletImpact over to EventWeaponFire)

- lang/Jailbreak.English/RTD/RTDLocale.cs
- mod/Jailbreak.RTD/AutoRTD.cs
- public/Jailbreak.Formatting/Views/RTD/IRTDLocale.cs
Added some debugging messages to chat so that I can view the state of the variable values at runtime
> Debugging Messages For AutoRTD

- mod/Jailbreak.RTD/AutoRTD.cs
Temporarily remove permission checking for Auto RTD to allow for debugging
> Remove Permission Check For Debugging

- mod/Jailbreak.RTD/AutoRTD.cs
Verbose value setting and debug print outs
> Sanity check debugging

- mod/Jailbreak.Debug/DebugCommand.cs
- mod/Jailbreak.LastRequest/LastRequestRebelCommand.cs
- mod/Jailbreak.LastRequest/LastRequests/GunToss.cs
- mod/Jailbreak.Rebel/RebelListener.cs
- mod/Jailbreak.Warden/Commands/CountdownCommandBehavior.cs
- mod/Jailbreak.Warden/WardenServiceExtension.cs
- Restricted !rebel to only be usable as the last prisoner alive
- Re-added additional HP to CTs within gun toss LRs
> Rebel and LR Balancing
